jobs:
  include:
    - stage: "Documentation"
      language: julia
      julia: 1.0
      os: linux
      script:
        -julia using Pkg; Pkg.add("Documenter")
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success:
         skip
