jobs:
  include:
    - stage: "Documentation"
      language: julia
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success:
         - julia -e 'Pkg.add("Documenter"); Pkg.add("Literate")'
